name: g2_fullstack497
services:
  postgres:
    image: postgres:16-alpine
    container_name: g2_db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g2_fullstack-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
#  backend:
#    container_name: g2_backend
#    build: .
#    ports:
#      - 3000:${PORT}
#    depends_on:
#      - postgres
#    environment:
#      - DATABASE_DSN = ${DATABASE_DSN}
  minio:
    image: minio/minio
    container_name: g2_fullstack497_minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - 9000:${MINIO_PORT1}
      - 9001:${MINIO_PORT2}
    volumes:
      - minio-data:/data
      #- g2_fullstack497r-data:/var/lib/minio/data
networks:
  g2_fullstack-net: # Check by using `docker network ls` command
    external: true
volumes:
  g2_fullstack-data:
  minio-data: