name: g2_fullstack497
services:
  postgres:
    image: postgres:16-alpine
    container_name: g2_db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - g2_fullstack-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  backend:
    container_name: g2_backend
    build: .
    ports:
      - 3000:${PORT}
    depends_on:
      - postgres
    environment:
      - DATABASE_DSN = ${DATABASE_DSN}
networks:
  g2_fullstack-net: # Check by using `docker network ls` command
    external: true
volumes:
  g2_fullstack-data: